#!/bin/sh
#
 
start() {
  start-stop-daemon -S -p /var/run/hostapd.pid --exec hostapd -- /etc/hostapd/hostapd.conf
}
 
stop() {
  start-stop-daemon --K -p /var/run/hostapd.pid
}
 
case "$1" in
start)
        start
        ;;
 
stop)
        stop
        ;;
restart)
        stop && start
        ;;
*)
        echo "Usage $0 {start|stop|restart}"
        exit 1
esac
 
exit 0
