#!/bin/busybox sh

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

busybox --install -s

# Do your stuff here.
clear
echo "This script mounts rootfs and boots it up, nothing more!"
sleep 2

ls /

ls /dev

# Mount the root filesystem.
mount -o rw /dev/hda2 /mnt/root

# Clean up.
umount /proc
umount /sys
umount /dev

# Boot the real thing.
exec switch_root /mnt/root /sbin/init
